# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'pingmainwindow.ui'
#
# Created: Thu Mar 20 23:36:55 2014
#      by: pyside-uic 0.2.14 running on PySide 1.2.0
#
# WARNING! All changes made in this file will be lost!

from PySide import QtCore, QtGui

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(679, 508)
        MainWindow.setMaximumSize(QtCore.QSize(679, 508))
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.tabWidget = QtGui.QTabWidget(self.centralwidget)
        self.tabWidget.setGeometry(QtCore.QRect(10, 10, 661, 481))
        self.tabWidget.setAutoFillBackground(False)
        self.tabWidget.setTabPosition(QtGui.QTabWidget.North)
        self.tabWidget.setTabShape(QtGui.QTabWidget.Rounded)
        self.tabWidget.setObjectName("tabWidget")
        self.ping = QtGui.QWidget()
        self.ping.setObjectName("ping")
        self.hostLabel = QtGui.QLabel(self.ping)
        self.hostLabel.setGeometry(QtCore.QRect(16, 12, 114, 16))
        self.hostLabel.setObjectName("hostLabel")
        self.pingBtn = QtGui.QPushButton(self.ping)
        self.pingBtn.setEnabled(False)
        self.pingBtn.setGeometry(QtCore.QRect(340, 12, 75, 23))
        self.pingBtn.setObjectName("pingBtn")
        self.hostLineEdit = QtGui.QLineEdit(self.ping)
        self.hostLineEdit.setGeometry(QtCore.QRect(136, 13, 171, 20))
        self.hostLineEdit.setObjectName("hostLineEdit")
        self.stopBtn = QtGui.QPushButton(self.ping)
        self.stopBtn.setEnabled(False)
        self.stopBtn.setGeometry(QtCore.QRect(450, 12, 75, 23))
        self.stopBtn.setObjectName("stopBtn")
        self.saveBtn = QtGui.QPushButton(self.ping)
        self.saveBtn.setEnabled(False)
        self.saveBtn.setGeometry(QtCore.QRect(560, 12, 75, 23))
        self.saveBtn.setObjectName("saveBtn")
        self.splitter = QtGui.QSplitter(self.ping)
        self.splitter.setGeometry(QtCore.QRect(6, 43, 641, 401))
        self.splitter.setOrientation(QtCore.Qt.Vertical)
        self.splitter.setObjectName("splitter")
        self.statusTable = QtGui.QTableWidget(self.splitter)
        self.statusTable.setFrameShape(QtGui.QFrame.StyledPanel)
        self.statusTable.setFrameShadow(QtGui.QFrame.Plain)
        self.statusTable.setShowGrid(True)
        self.statusTable.setRowCount(0)
        self.statusTable.setColumnCount(8)
        self.statusTable.setObjectName("statusTable")
        self.statusTable.setColumnCount(8)
        self.statusTable.setRowCount(0)
        item = QtGui.QTableWidgetItem()
        self.statusTable.setHorizontalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self.statusTable.setHorizontalHeaderItem(1, item)
        item = QtGui.QTableWidgetItem()
        self.statusTable.setHorizontalHeaderItem(2, item)
        item = QtGui.QTableWidgetItem()
        self.statusTable.setHorizontalHeaderItem(3, item)
        item = QtGui.QTableWidgetItem()
        self.statusTable.setHorizontalHeaderItem(4, item)
        item = QtGui.QTableWidgetItem()
        self.statusTable.setHorizontalHeaderItem(5, item)
        item = QtGui.QTableWidgetItem()
        self.statusTable.setHorizontalHeaderItem(6, item)
        item = QtGui.QTableWidgetItem()
        self.statusTable.setHorizontalHeaderItem(7, item)
        self.runTable = QtGui.QTableWidget(self.splitter)
        self.runTable.setObjectName("runTable")
        self.runTable.setColumnCount(6)
        self.runTable.setRowCount(0)
        item = QtGui.QTableWidgetItem()
        self.runTable.setHorizontalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self.runTable.setHorizontalHeaderItem(1, item)
        item = QtGui.QTableWidgetItem()
        self.runTable.setHorizontalHeaderItem(2, item)
        item = QtGui.QTableWidgetItem()
        self.runTable.setHorizontalHeaderItem(3, item)
        item = QtGui.QTableWidgetItem()
        self.runTable.setHorizontalHeaderItem(4, item)
        item = QtGui.QTableWidgetItem()
        self.runTable.setHorizontalHeaderItem(5, item)
        self.tabWidget.addTab(self.ping, "")
        self.alerts = QtGui.QWidget()
        self.alerts.setObjectName("alerts")
        self.alertGroupBox = QtGui.QGroupBox(self.alerts)
        self.alertGroupBox.setGeometry(QtCore.QRect(30, 20, 271, 61))
        self.alertGroupBox.setObjectName("alertGroupBox")
        self.widget = QtGui.QWidget(self.alertGroupBox)
        self.widget.setGeometry(QtCore.QRect(10, 10, 206, 40))
        self.widget.setObjectName("widget")
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.widget)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.onlineRadio = QtGui.QRadioButton(self.widget)
        self.onlineRadio.setObjectName("onlineRadio")
        self.horizontalLayout_2.addWidget(self.onlineRadio)
        self.offlineRadio = QtGui.QRadioButton(self.widget)
        self.offlineRadio.setObjectName("offlineRadio")
        self.horizontalLayout_2.addWidget(self.offlineRadio)
        self.donotalertRadio = QtGui.QRadioButton(self.widget)
        self.donotalertRadio.setObjectName("donotalertRadio")
        self.horizontalLayout_2.addWidget(self.donotalertRadio)
        self.verticalLayout_2.addLayout(self.horizontalLayout_2)
        self.notificationGroupBox = QtGui.QGroupBox(self.alerts)
        self.notificationGroupBox.setGeometry(QtCore.QRect(30, 120, 271, 121))
        self.notificationGroupBox.setObjectName("notificationGroupBox")
        self.soundCheckBox = QtGui.QCheckBox(self.notificationGroupBox)
        self.soundCheckBox.setGeometry(QtCore.QRect(20, 50, 76, 17))
        self.soundCheckBox.setObjectName("soundCheckBox")
        self.widget1 = QtGui.QWidget(self.notificationGroupBox)
        self.widget1.setGeometry(QtCore.QRect(20, 20, 231, 19))
        self.widget1.setObjectName("widget1")
        self.horizontalLayout_3 = QtGui.QHBoxLayout(self.widget1)
        self.horizontalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.dialogRadio = QtGui.QRadioButton(self.widget1)
        self.dialogRadio.setObjectName("dialogRadio")
        self.horizontalLayout_3.addWidget(self.dialogRadio)
        self.toastRadio = QtGui.QRadioButton(self.widget1)
        self.toastRadio.setObjectName("toastRadio")
        self.horizontalLayout_3.addWidget(self.toastRadio)
        self.widget2 = QtGui.QWidget(self.notificationGroupBox)
        self.widget2.setGeometry(QtCore.QRect(20, 80, 241, 22))
        self.widget2.setObjectName("widget2")
        self.horizontalLayout_4 = QtGui.QHBoxLayout(self.widget2)
        self.horizontalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.emailLabel = QtGui.QLabel(self.widget2)
        self.emailLabel.setObjectName("emailLabel")
        self.horizontalLayout_4.addWidget(self.emailLabel)
        self.emailLineEdit = QtGui.QLineEdit(self.widget2)
        self.emailLineEdit.setObjectName("emailLineEdit")
        self.horizontalLayout_4.addWidget(self.emailLineEdit)
        self.applyAlertBtn = QtGui.QPushButton(self.alerts)
        self.applyAlertBtn.setGeometry(QtCore.QRect(340, 390, 75, 23))
        self.applyAlertBtn.setObjectName("applyAlertBtn")
        self.saveAlertBtn = QtGui.QPushButton(self.alerts)
        self.saveAlertBtn.setGeometry(QtCore.QRect(440, 390, 75, 23))
        self.saveAlertBtn.setObjectName("saveAlertBtn")
        self.defaultsAlertBtn = QtGui.QPushButton(self.alerts)
        self.defaultsAlertBtn.setGeometry(QtCore.QRect(540, 390, 75, 23))
        self.defaultsAlertBtn.setObjectName("defaultsAlertBtn")
        self.tabWidget.addTab(self.alerts, "")
        self.settings = QtGui.QWidget()
        self.settings.setObjectName("settings")
        self.applySetBtn = QtGui.QPushButton(self.settings)
        self.applySetBtn.setGeometry(QtCore.QRect(340, 390, 75, 23))
        self.applySetBtn.setObjectName("applySetBtn")
        self.saveSetBtn = QtGui.QPushButton(self.settings)
        self.saveSetBtn.setGeometry(QtCore.QRect(440, 390, 75, 23))
        self.saveSetBtn.setObjectName("saveSetBtn")
        self.defaultsSetBtn = QtGui.QPushButton(self.settings)
        self.defaultsSetBtn.setGeometry(QtCore.QRect(540, 390, 75, 23))
        self.defaultsSetBtn.setObjectName("defaultsSetBtn")
        self.widget3 = QtGui.QWidget(self.settings)
        self.widget3.setGeometry(QtCore.QRect(20, 30, 341, 81))
        self.widget3.setObjectName("widget3")
        self.gridLayout_2 = QtGui.QGridLayout(self.widget3)
        self.gridLayout_2.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.timebtwlabel = QtGui.QLabel(self.widget3)
        self.timebtwlabel.setObjectName("timebtwlabel")
        self.gridLayout_2.addWidget(self.timebtwlabel, 0, 0, 1, 1)
        self.timebtwLineEdit = QtGui.QLineEdit(self.widget3)
        self.timebtwLineEdit.setObjectName("timebtwLineEdit")
        self.gridLayout_2.addWidget(self.timebtwLineEdit, 0, 1, 1, 1)
        self.ttlLabel = QtGui.QLabel(self.widget3)
        self.ttlLabel.setObjectName("ttlLabel")
        self.gridLayout_2.addWidget(self.ttlLabel, 1, 0, 1, 1)
        self.ttlLineEdit = QtGui.QLineEdit(self.widget3)
        self.ttlLineEdit.setObjectName("ttlLineEdit")
        self.gridLayout_2.addWidget(self.ttlLineEdit, 1, 1, 1, 1)
        self.packetLabel = QtGui.QLabel(self.widget3)
        self.packetLabel.setObjectName("packetLabel")
        self.gridLayout_2.addWidget(self.packetLabel, 2, 0, 1, 1)
        self.packetsizeLineEdit = QtGui.QLineEdit(self.widget3)
        self.packetsizeLineEdit.setObjectName("packetsizeLineEdit")
        self.gridLayout_2.addWidget(self.packetsizeLineEdit, 2, 1, 1, 1)
        self.tabWidget.addTab(self.settings, "")
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtGui.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.hostLabel.setBuddy(self.hostLineEdit)
        self.emailLabel.setBuddy(self.emailLineEdit)
        self.timebtwlabel.setBuddy(self.timebtwLineEdit)
        self.ttlLabel.setBuddy(self.ttlLineEdit)
        self.packetLabel.setBuddy(self.packetsizeLineEdit)

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
        MainWindow.setTabOrder(self.tabWidget, self.hostLineEdit)
        MainWindow.setTabOrder(self.hostLineEdit, self.pingBtn)
        MainWindow.setTabOrder(self.pingBtn, self.stopBtn)
        MainWindow.setTabOrder(self.stopBtn, self.saveBtn)
        MainWindow.setTabOrder(self.saveBtn, self.statusTable)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QtGui.QApplication.translate("MainWindow", "Ping Utility", None, QtGui.QApplication.UnicodeUTF8))
        self.hostLabel.setText(QtGui.QApplication.translate("MainWindow", "Hostname / IP Address:", None, QtGui.QApplication.UnicodeUTF8))
        self.pingBtn.setText(QtGui.QApplication.translate("MainWindow", "Ping", None, QtGui.QApplication.UnicodeUTF8))
        self.stopBtn.setText(QtGui.QApplication.translate("MainWindow", "Stop", None, QtGui.QApplication.UnicodeUTF8))
        self.saveBtn.setText(QtGui.QApplication.translate("MainWindow", "Save", None, QtGui.QApplication.UnicodeUTF8))
        self.statusTable.horizontalHeaderItem(0).setText(QtGui.QApplication.translate("MainWindow", "Hostname", None, QtGui.QApplication.UnicodeUTF8))
        self.statusTable.horizontalHeaderItem(1).setText(QtGui.QApplication.translate("MainWindow", "IP Address", None, QtGui.QApplication.UnicodeUTF8))
        self.statusTable.horizontalHeaderItem(2).setText(QtGui.QApplication.translate("MainWindow", "Status", None, QtGui.QApplication.UnicodeUTF8))
        self.statusTable.horizontalHeaderItem(3).setText(QtGui.QApplication.translate("MainWindow", "Packets Sent", None, QtGui.QApplication.UnicodeUTF8))
        self.statusTable.horizontalHeaderItem(4).setText(QtGui.QApplication.translate("MainWindow", "Packets Recieved", None, QtGui.QApplication.UnicodeUTF8))
        self.statusTable.horizontalHeaderItem(5).setText(QtGui.QApplication.translate("MainWindow", "Min Time", None, QtGui.QApplication.UnicodeUTF8))
        self.statusTable.horizontalHeaderItem(6).setText(QtGui.QApplication.translate("MainWindow", "Max Time", None, QtGui.QApplication.UnicodeUTF8))
        self.statusTable.horizontalHeaderItem(7).setText(QtGui.QApplication.translate("MainWindow", "Avg Time", None, QtGui.QApplication.UnicodeUTF8))
        self.runTable.horizontalHeaderItem(0).setText(QtGui.QApplication.translate("MainWindow", "Time", None, QtGui.QApplication.UnicodeUTF8))
        self.runTable.horizontalHeaderItem(1).setText(QtGui.QApplication.translate("MainWindow", "Host IP Address", None, QtGui.QApplication.UnicodeUTF8))
        self.runTable.horizontalHeaderItem(2).setText(QtGui.QApplication.translate("MainWindow", "Status", None, QtGui.QApplication.UnicodeUTF8))
        self.runTable.horizontalHeaderItem(3).setText(QtGui.QApplication.translate("MainWindow", "Bytes", None, QtGui.QApplication.UnicodeUTF8))
        self.runTable.horizontalHeaderItem(4).setText(QtGui.QApplication.translate("MainWindow", "Trip Time(ms)", None, QtGui.QApplication.UnicodeUTF8))
        self.runTable.horizontalHeaderItem(5).setText(QtGui.QApplication.translate("MainWindow", "TTL", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.ping), QtGui.QApplication.translate("MainWindow", "Ping", None, QtGui.QApplication.UnicodeUTF8))
        self.alertGroupBox.setTitle(QtGui.QApplication.translate("MainWindow", "Alert when host is:", None, QtGui.QApplication.UnicodeUTF8))
        self.onlineRadio.setText(QtGui.QApplication.translate("MainWindow", "Online", None, QtGui.QApplication.UnicodeUTF8))
        self.offlineRadio.setText(QtGui.QApplication.translate("MainWindow", "Offline", None, QtGui.QApplication.UnicodeUTF8))
        self.donotalertRadio.setText(QtGui.QApplication.translate("MainWindow", "Do Not Alert", None, QtGui.QApplication.UnicodeUTF8))
        self.notificationGroupBox.setTitle(QtGui.QApplication.translate("MainWindow", "Notifications", None, QtGui.QApplication.UnicodeUTF8))
        self.soundCheckBox.setText(QtGui.QApplication.translate("MainWindow", "Play Sound", None, QtGui.QApplication.UnicodeUTF8))
        self.dialogRadio.setText(QtGui.QApplication.translate("MainWindow", "Pop up Dialog", None, QtGui.QApplication.UnicodeUTF8))
        self.toastRadio.setText(QtGui.QApplication.translate("MainWindow", "Toast Pop up", None, QtGui.QApplication.UnicodeUTF8))
        self.emailLabel.setText(QtGui.QApplication.translate("MainWindow", "Send Email To:", None, QtGui.QApplication.UnicodeUTF8))
        self.applyAlertBtn.setText(QtGui.QApplication.translate("MainWindow", "Apply", None, QtGui.QApplication.UnicodeUTF8))
        self.saveAlertBtn.setText(QtGui.QApplication.translate("MainWindow", "Save", None, QtGui.QApplication.UnicodeUTF8))
        self.defaultsAlertBtn.setText(QtGui.QApplication.translate("MainWindow", "Defaults", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.alerts), QtGui.QApplication.translate("MainWindow", "Alerts", None, QtGui.QApplication.UnicodeUTF8))
        self.applySetBtn.setText(QtGui.QApplication.translate("MainWindow", "Apply", None, QtGui.QApplication.UnicodeUTF8))
        self.saveSetBtn.setText(QtGui.QApplication.translate("MainWindow", "Save", None, QtGui.QApplication.UnicodeUTF8))
        self.defaultsSetBtn.setText(QtGui.QApplication.translate("MainWindow", "Defaults", None, QtGui.QApplication.UnicodeUTF8))
        self.timebtwlabel.setText(QtGui.QApplication.translate("MainWindow", "TIme Between Pings(ms):", None, QtGui.QApplication.UnicodeUTF8))
        self.ttlLabel.setText(QtGui.QApplication.translate("MainWindow", "TTL:", None, QtGui.QApplication.UnicodeUTF8))
        self.packetLabel.setText(QtGui.QApplication.translate("MainWindow", "Packet Size:", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.settings), QtGui.QApplication.translate("MainWindow", "Settings", None, QtGui.QApplication.UnicodeUTF8))

