# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'pingmainwindow.ui'
#
# Created: Thu Mar 20 20:25:16 2014
#      by: PyQt4 UI code generator 4.9.1
#
# WARNING! All changes made in this file will be lost!

from PySide import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    _fromUtf8 = lambda s: s

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.resize(679, 508)
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.tabWidget = QtGui.QTabWidget(self.centralwidget)
        self.tabWidget.setGeometry(QtCore.QRect(10, 0, 661, 481))
        self.tabWidget.setObjectName(_fromUtf8("tabWidget"))
        self.ping = QtGui.QWidget()
        self.ping.setObjectName(_fromUtf8("ping"))
        self.widget = QtGui.QWidget(self.ping)
        self.widget.setGeometry(QtCore.QRect(13, 13, 631, 430))
        self.widget.setObjectName(_fromUtf8("widget"))
        self.gridLayout_4 = QtGui.QGridLayout(self.widget)
        self.gridLayout_4.setMargin(0)
        self.gridLayout_4.setObjectName(_fromUtf8("gridLayout_4"))
        self.gridLayout_3 = QtGui.QGridLayout()
        self.gridLayout_3.setObjectName(_fromUtf8("gridLayout_3"))
        self.hostLabel = QtGui.QLabel(self.widget)
        self.hostLabel.setObjectName(_fromUtf8("hostLabel"))
        self.gridLayout_3.addWidget(self.hostLabel, 0, 0, 1, 1)
        self.hostLineEdit = QtGui.QLineEdit(self.widget)
        self.hostLineEdit.setObjectName(_fromUtf8("hostLineEdit"))
        self.gridLayout_3.addWidget(self.hostLineEdit, 0, 1, 1, 1)
        spacerItem = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout_3.addItem(spacerItem, 0, 2, 1, 1)
        self.pingBtn = QtGui.QPushButton(self.widget)
        self.pingBtn.setEnabled(False)
        self.pingBtn.setObjectName(_fromUtf8("pingBtn"))
        self.gridLayout_3.addWidget(self.pingBtn, 0, 3, 1, 1)
        self.stopBtn = QtGui.QPushButton(self.widget)
        self.stopBtn.setEnabled(False)
        self.stopBtn.setObjectName(_fromUtf8("stopBtn"))
        self.gridLayout_3.addWidget(self.stopBtn, 0, 4, 1, 1)
        self.saveBtn = QtGui.QPushButton(self.widget)
        self.saveBtn.setEnabled(False)
        self.saveBtn.setObjectName(_fromUtf8("saveBtn"))
        self.gridLayout_3.addWidget(self.saveBtn, 0, 5, 1, 1)
        self.gridLayout_4.addLayout(self.gridLayout_3, 0, 0, 1, 1)
        self.statusTable = QtGui.QTableWidget(self.widget)
        self.statusTable.setShowGrid(True)
        self.statusTable.setRowCount(1)
        self.statusTable.setColumnCount(8)
        self.statusTable.setObjectName(_fromUtf8("statusTable"))
        item = QtGui.QTableWidgetItem()
        self.statusTable.setVerticalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self.statusTable.setHorizontalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self.statusTable.setHorizontalHeaderItem(1, item)
        item = QtGui.QTableWidgetItem()
        self.statusTable.setHorizontalHeaderItem(2, item)
        item = QtGui.QTableWidgetItem()
        self.statusTable.setHorizontalHeaderItem(3, item)
        item = QtGui.QTableWidgetItem()
        self.statusTable.setHorizontalHeaderItem(4, item)
        item = QtGui.QTableWidgetItem()
        self.statusTable.setHorizontalHeaderItem(5, item)
        item = QtGui.QTableWidgetItem()
        self.statusTable.setHorizontalHeaderItem(6, item)
        item = QtGui.QTableWidgetItem()
        self.statusTable.setHorizontalHeaderItem(7, item)
        item = QtGui.QTableWidgetItem()
        item.setFlags(QtCore.Qt.ItemIsEnabled)
        self.statusTable.setItem(0, 0, item)
        item = QtGui.QTableWidgetItem()
        item.setFlags(QtCore.Qt.ItemIsEnabled)
        self.statusTable.setItem(0, 1, item)
        item = QtGui.QTableWidgetItem()
        item.setFlags(QtCore.Qt.ItemIsEnabled)
        self.statusTable.setItem(0, 2, item)
        item = QtGui.QTableWidgetItem()
        item.setFlags(QtCore.Qt.ItemIsEnabled)
        self.statusTable.setItem(0, 3, item)
        item = QtGui.QTableWidgetItem()
        item.setFlags(QtCore.Qt.ItemIsEnabled)
        self.statusTable.setItem(0, 4, item)
        item = QtGui.QTableWidgetItem()
        item.setFlags(QtCore.Qt.ItemIsEnabled)
        self.statusTable.setItem(0, 5, item)
        item = QtGui.QTableWidgetItem()
        item.setFlags(QtCore.Qt.ItemIsEnabled)
        self.statusTable.setItem(0, 6, item)
        item = QtGui.QTableWidgetItem()
        item.setFlags(QtCore.Qt.ItemIsEnabled)
        self.statusTable.setItem(0, 7, item)
        self.gridLayout_4.addWidget(self.statusTable, 1, 0, 1, 1)
        self.runTable = QtGui.QTableWidget(self.widget)
        self.runTable.setObjectName(_fromUtf8("runTable"))
        self.runTable.setColumnCount(6)
        self.runTable.setRowCount(0)
        item = QtGui.QTableWidgetItem()
        self.runTable.setHorizontalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self.runTable.setHorizontalHeaderItem(1, item)
        item = QtGui.QTableWidgetItem()
        self.runTable.setHorizontalHeaderItem(2, item)
        item = QtGui.QTableWidgetItem()
        self.runTable.setHorizontalHeaderItem(3, item)
        item = QtGui.QTableWidgetItem()
        self.runTable.setHorizontalHeaderItem(4, item)
        item = QtGui.QTableWidgetItem()
        self.runTable.setHorizontalHeaderItem(5, item)
        self.gridLayout_4.addWidget(self.runTable, 2, 0, 1, 1)
        self.tabWidget.addTab(self.ping, _fromUtf8(""))
        self.alerts = QtGui.QWidget()
        self.alerts.setObjectName(_fromUtf8("alerts"))
        self.widget1 = QtGui.QWidget(self.alerts)
        self.widget1.setGeometry(QtCore.QRect(10, 20, 301, 261))
        self.widget1.setObjectName(_fromUtf8("widget1"))
        self.gridLayout = QtGui.QGridLayout(self.widget1)
        self.gridLayout.setMargin(0)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.formLayout = QtGui.QFormLayout()
        self.formLayout.setObjectName(_fromUtf8("formLayout"))
        self.alertLabel = QtGui.QLabel(self.widget1)
        self.alertLabel.setObjectName(_fromUtf8("alertLabel"))
        self.formLayout.setWidget(0, QtGui.QFormLayout.LabelRole, self.alertLabel)
        self.onlineRadio = QtGui.QRadioButton(self.widget1)
        self.onlineRadio.setObjectName(_fromUtf8("onlineRadio"))
        self.formLayout.setWidget(2, QtGui.QFormLayout.LabelRole, self.onlineRadio)
        self.offlineRadio = QtGui.QRadioButton(self.widget1)
        self.offlineRadio.setObjectName(_fromUtf8("offlineRadio"))
        self.formLayout.setWidget(3, QtGui.QFormLayout.LabelRole, self.offlineRadio)
        self.donotalertRadio = QtGui.QRadioButton(self.widget1)
        self.donotalertRadio.setObjectName(_fromUtf8("donotalertRadio"))
        self.formLayout.setWidget(4, QtGui.QFormLayout.LabelRole, self.donotalertRadio)
        self.gridLayout.addLayout(self.formLayout, 0, 0, 1, 4)
        self.notificationLabel = QtGui.QLabel(self.widget1)
        self.notificationLabel.setObjectName(_fromUtf8("notificationLabel"))
        self.gridLayout.addWidget(self.notificationLabel, 1, 0, 1, 1)
        self.formLayout_2 = QtGui.QFormLayout()
        self.formLayout_2.setObjectName(_fromUtf8("formLayout_2"))
        self.dialogRadio = QtGui.QRadioButton(self.widget1)
        self.dialogRadio.setObjectName(_fromUtf8("dialogRadio"))
        self.formLayout_2.setWidget(0, QtGui.QFormLayout.LabelRole, self.dialogRadio)
        self.toastRadio = QtGui.QRadioButton(self.widget1)
        self.toastRadio.setObjectName(_fromUtf8("toastRadio"))
        self.formLayout_2.setWidget(0, QtGui.QFormLayout.FieldRole, self.toastRadio)
        self.gridLayout.addLayout(self.formLayout_2, 2, 0, 1, 3)
        self.soundCheckBox = QtGui.QCheckBox(self.widget1)
        self.soundCheckBox.setObjectName(_fromUtf8("soundCheckBox"))
        self.gridLayout.addWidget(self.soundCheckBox, 3, 0, 1, 3)
        self.emailLabel = QtGui.QLabel(self.widget1)
        self.emailLabel.setObjectName(_fromUtf8("emailLabel"))
        self.gridLayout.addWidget(self.emailLabel, 4, 0, 1, 1)
        self.emailLineEdit = QtGui.QLineEdit(self.widget1)
        self.emailLineEdit.setObjectName(_fromUtf8("emailLineEdit"))
        self.gridLayout.addWidget(self.emailLineEdit, 4, 1, 1, 3)
        self.applyBtn = QtGui.QPushButton(self.widget1)
        self.applyBtn.setObjectName(_fromUtf8("applyBtn"))
        self.gridLayout.addWidget(self.applyBtn, 5, 0, 1, 2)
        self.saveAlertBtn = QtGui.QPushButton(self.widget1)
        self.saveAlertBtn.setObjectName(_fromUtf8("saveAlertBtn"))
        self.gridLayout.addWidget(self.saveAlertBtn, 5, 2, 1, 1)
        self.defaultsBtn = QtGui.QPushButton(self.widget1)
        self.defaultsBtn.setObjectName(_fromUtf8("defaultsBtn"))
        self.gridLayout.addWidget(self.defaultsBtn, 5, 3, 1, 1)
        self.tabWidget.addTab(self.alerts, _fromUtf8(""))
        self.settings = QtGui.QWidget()
        self.settings.setObjectName(_fromUtf8("settings"))
        self.gridLayout_2 = QtGui.QGridLayout(self.settings)
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.timebtwlabel = QtGui.QLabel(self.settings)
        self.timebtwlabel.setObjectName(_fromUtf8("timebtwlabel"))
        self.gridLayout_2.addWidget(self.timebtwlabel, 0, 0, 1, 2)
        self.timebtwLineEdit = QtGui.QLineEdit(self.settings)
        self.timebtwLineEdit.setObjectName(_fromUtf8("timebtwLineEdit"))
        self.gridLayout_2.addWidget(self.timebtwLineEdit, 0, 2, 1, 2)
        self.ttlLabel = QtGui.QLabel(self.settings)
        self.ttlLabel.setObjectName(_fromUtf8("ttlLabel"))
        self.gridLayout_2.addWidget(self.ttlLabel, 1, 0, 1, 1)
        self.ttlLineEdit = QtGui.QLineEdit(self.settings)
        self.ttlLineEdit.setObjectName(_fromUtf8("ttlLineEdit"))
        self.gridLayout_2.addWidget(self.ttlLineEdit, 1, 2, 1, 2)
        self.packetLabel = QtGui.QLabel(self.settings)
        self.packetLabel.setObjectName(_fromUtf8("packetLabel"))
        self.gridLayout_2.addWidget(self.packetLabel, 2, 0, 1, 1)
        self.packetsizeLineEdit = QtGui.QLineEdit(self.settings)
        self.packetsizeLineEdit.setObjectName(_fromUtf8("packetsizeLineEdit"))
        self.gridLayout_2.addWidget(self.packetsizeLineEdit, 2, 2, 1, 2)
        self.applysetBtn = QtGui.QPushButton(self.settings)
        self.applysetBtn.setObjectName(_fromUtf8("applysetBtn"))
        self.gridLayout_2.addWidget(self.applysetBtn, 3, 0, 1, 1)
        self.savesetBtn = QtGui.QPushButton(self.settings)
        self.savesetBtn.setObjectName(_fromUtf8("savesetBtn"))
        self.gridLayout_2.addWidget(self.savesetBtn, 3, 1, 1, 2)
        self.defaultssetBtn = QtGui.QPushButton(self.settings)
        self.defaultssetBtn.setObjectName(_fromUtf8("defaultssetBtn"))
        self.gridLayout_2.addWidget(self.defaultssetBtn, 3, 3, 1, 1)
        self.tabWidget.addTab(self.settings, _fromUtf8(""))
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtGui.QStatusBar(MainWindow)
        self.statusbar.setObjectName(_fromUtf8("statusbar"))
        MainWindow.setStatusBar(self.statusbar)
        self.hostLabel.setBuddy(self.hostLineEdit)
        self.alertLabel.setBuddy(self.onlineRadio)
        self.notificationLabel.setBuddy(self.dialogRadio)
        self.emailLabel.setBuddy(self.emailLineEdit)
        self.timebtwlabel.setBuddy(self.timebtwLineEdit)
        self.ttlLabel.setBuddy(self.ttlLineEdit)
        self.packetLabel.setBuddy(self.packetsizeLineEdit)

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
        MainWindow.setTabOrder(self.tabWidget, self.hostLineEdit)
        MainWindow.setTabOrder(self.hostLineEdit, self.pingBtn)
        MainWindow.setTabOrder(self.pingBtn, self.stopBtn)
        MainWindow.setTabOrder(self.stopBtn, self.saveBtn)
        MainWindow.setTabOrder(self.saveBtn, self.statusTable)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QtGui.QApplication.translate("MainWindow", "MainWindow", None, QtGui.QApplication.UnicodeUTF8))
        self.hostLabel.setText(QtGui.QApplication.translate("MainWindow", "Hostname / IP Address:", None, QtGui.QApplication.UnicodeUTF8))
        self.pingBtn.setText(QtGui.QApplication.translate("MainWindow", "Ping", None, QtGui.QApplication.UnicodeUTF8))
        self.stopBtn.setText(QtGui.QApplication.translate("MainWindow", "Stop", None, QtGui.QApplication.UnicodeUTF8))
        self.saveBtn.setText(QtGui.QApplication.translate("MainWindow", "Save", None, QtGui.QApplication.UnicodeUTF8))
        item = self.statusTable.horizontalHeaderItem(0)
        item.setText(QtGui.QApplication.translate("MainWindow", "Hostname", None, QtGui.QApplication.UnicodeUTF8))
        item = self.statusTable.horizontalHeaderItem(1)
        item.setText(QtGui.QApplication.translate("MainWindow", "IP Address", None, QtGui.QApplication.UnicodeUTF8))
        item = self.statusTable.horizontalHeaderItem(2)
        item.setText(QtGui.QApplication.translate("MainWindow", "Status", None, QtGui.QApplication.UnicodeUTF8))
        item = self.statusTable.horizontalHeaderItem(3)
        item.setText(QtGui.QApplication.translate("MainWindow", "Packets Sent", None, QtGui.QApplication.UnicodeUTF8))
        item = self.statusTable.horizontalHeaderItem(4)
        item.setText(QtGui.QApplication.translate("MainWindow", "Packets Recieved", None, QtGui.QApplication.UnicodeUTF8))
        item = self.statusTable.horizontalHeaderItem(5)
        item.setText(QtGui.QApplication.translate("MainWindow", "Min Time", None, QtGui.QApplication.UnicodeUTF8))
        item = self.statusTable.horizontalHeaderItem(6)
        item.setText(QtGui.QApplication.translate("MainWindow", "Max Time", None, QtGui.QApplication.UnicodeUTF8))
        item = self.statusTable.horizontalHeaderItem(7)
        item.setText(QtGui.QApplication.translate("MainWindow", "Avg Time", None, QtGui.QApplication.UnicodeUTF8))
        __sortingEnabled = self.statusTable.isSortingEnabled()
        self.statusTable.setSortingEnabled(False)
        self.statusTable.setSortingEnabled(__sortingEnabled)
        item = self.runTable.horizontalHeaderItem(0)
        item.setText(QtGui.QApplication.translate("MainWindow", "Time", None, QtGui.QApplication.UnicodeUTF8))
        item = self.runTable.horizontalHeaderItem(1)
        item.setText(QtGui.QApplication.translate("MainWindow", "Host IP Address", None, QtGui.QApplication.UnicodeUTF8))
        item = self.runTable.horizontalHeaderItem(2)
        item.setText(QtGui.QApplication.translate("MainWindow", "Status", None, QtGui.QApplication.UnicodeUTF8))
        item = self.runTable.horizontalHeaderItem(3)
        item.setText(QtGui.QApplication.translate("MainWindow", "Bytes", None, QtGui.QApplication.UnicodeUTF8))
        item = self.runTable.horizontalHeaderItem(4)
        item.setText(QtGui.QApplication.translate("MainWindow", "Trip Time(ms)", None, QtGui.QApplication.UnicodeUTF8))
        item = self.runTable.horizontalHeaderItem(5)
        item.setText(QtGui.QApplication.translate("MainWindow", "TTL", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.ping), QtGui.QApplication.translate("MainWindow", "Ping", None, QtGui.QApplication.UnicodeUTF8))
        self.alertLabel.setText(QtGui.QApplication.translate("MainWindow", "Alert When:", None, QtGui.QApplication.UnicodeUTF8))
        self.onlineRadio.setText(QtGui.QApplication.translate("MainWindow", "Online", None, QtGui.QApplication.UnicodeUTF8))
        self.offlineRadio.setText(QtGui.QApplication.translate("MainWindow", "Offline", None, QtGui.QApplication.UnicodeUTF8))
        self.donotalertRadio.setText(QtGui.QApplication.translate("MainWindow", "Do Not Alert", None, QtGui.QApplication.UnicodeUTF8))
        self.notificationLabel.setText(QtGui.QApplication.translate("MainWindow", "Notifications", None, QtGui.QApplication.UnicodeUTF8))
        self.dialogRadio.setText(QtGui.QApplication.translate("MainWindow", "Pop up Dialog", None, QtGui.QApplication.UnicodeUTF8))
        self.toastRadio.setText(QtGui.QApplication.translate("MainWindow", "Toast Pop up", None, QtGui.QApplication.UnicodeUTF8))
        self.soundCheckBox.setText(QtGui.QApplication.translate("MainWindow", "Play Sound", None, QtGui.QApplication.UnicodeUTF8))
        self.emailLabel.setText(QtGui.QApplication.translate("MainWindow", "Send Email To:", None, QtGui.QApplication.UnicodeUTF8))
        self.applyBtn.setText(QtGui.QApplication.translate("MainWindow", "Apply", None, QtGui.QApplication.UnicodeUTF8))
        self.saveAlertBtn.setText(QtGui.QApplication.translate("MainWindow", "Save", None, QtGui.QApplication.UnicodeUTF8))
        self.defaultsBtn.setText(QtGui.QApplication.translate("MainWindow", "Defaults", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.alerts), QtGui.QApplication.translate("MainWindow", "Alerts", None, QtGui.QApplication.UnicodeUTF8))
        self.timebtwlabel.setText(QtGui.QApplication.translate("MainWindow", "TIme Between Pings(ms):", None, QtGui.QApplication.UnicodeUTF8))
        self.ttlLabel.setText(QtGui.QApplication.translate("MainWindow", "TTL:", None, QtGui.QApplication.UnicodeUTF8))
        self.packetLabel.setText(QtGui.QApplication.translate("MainWindow", "Packet Size:", None, QtGui.QApplication.UnicodeUTF8))
        self.applysetBtn.setText(QtGui.QApplication.translate("MainWindow", "Apply", None, QtGui.QApplication.UnicodeUTF8))
        self.savesetBtn.setText(QtGui.QApplication.translate("MainWindow", "Save", None, QtGui.QApplication.UnicodeUTF8))
        self.defaultssetBtn.setText(QtGui.QApplication.translate("MainWindow", "Defaults", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.settings), QtGui.QApplication.translate("MainWindow", "Settings", None, QtGui.QApplication.UnicodeUTF8))

